### PR TITLE
[merged] fixing build warnings/errors (missing documentation)

### PR DESCRIPTION
**Pull request by retaj**

### CODE REVIEW

**Comment by mschilli87** [comment]
@retaj: Once you got the build to work for this PR (by pushing fixes to the `docufix` branch), please don't merge it here.
Instead, I suggest to close this PR and merge `docufix` directly into `dev2` (as it's independent of the Travis-CI stuff I'm working on in this branch). If you prefer to that that through another PR or simply by a local `git checkout dev2 && git merge docufix && git branch -d docufix && git push origin dev2` doesn't matter.

---
Once this is done, I can rebase the `travis` branch on `dev2` (incl. your `docufix` changes) and keep working on that before we finally merge my changes back to `dev2` when I'm done testing.

**Comment by mschilli87** [comment]
There [warnings](https://travis-ci.org/BIMSBbioinfo/ciRcus/jobs/208272384#L3588)  still seem to be there....

@retaj: Does `R CMD check` work for you locally now?

**Comment by retaj** [comment]
Looks like it crashed due to some externality (a bioconductor package didn't download), I just reran the Travis build...will not merge to travis branch, just want to see it passing :)

**Comment by mschilli87** [comment]
Let's hope this is temporal and a single successful run caches all packages for the future then.

**Comment by retaj** [comment]
ran devtools::check(), it says:
R CMD check results
0 errors | 0 warnings | 3 notes

notes are mostly bs...complaining about .travis.yaml file :) and variables/functions with no visible global definition (fundamentalist way to say "you guys are using data.table and ggplot2") 🥇 

let's see what Travis has to say :)

**Comment by mschilli87** [comment]
still '[Undocumented code objects](https://travis-ci.org/BIMSBbioinfo/ciRcus/jobs/208272383#L3675)'...

**Comment by retaj** [comment]
No idea why R:oldrel is still crashing, it should be running 3.2.5 according to Travis [doc](https://docs.travis-ci.com/user/languages/r/#R-Versions). SummarizedExperiment [depends](https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html) on R >= 3.2. Whatevs, I restarted the R:oldrel build just in case it was some trivial issue - if it crashes again, feel free to drop the oldrel from .travis.yaml and set R >= 3.3 as a dependency for ciRcus :machiavelli:

**Comment by mschilli87** [comment]
Whatever the reason, `SummarizedExperiment` [seems to by unavailable](https://travis-ci.org/BIMSBbioinfo/ciRcus/jobs/208341924#L723) in [R 3.2.5](https://travis-ci.org/BIMSBbioinfo/ciRcus/jobs/208341924#L538).

---
Can you adjust the dependency R >= 3.3 in the `docufix` branch & merge it into `dev2`?

I'll keep care of dropping `oldrel` from Travis in the `travis` branch.

---
I'll close this now as all the information is here.

**Comment by mschilli87** [comment]
@retaj: Regarding the [notes complaining about `.travis.yml`](https://github.com/BIMSBbioinfo/ciRcus/pull/14#issuecomment-284519418):

[If I understood correctly](http://jtleek.com/protocols/travis_bioc_devel/) you can make R ignore it by adding the following to `.Rbuildignore`:

```
## Ignore travis config file
^\.travis\.yml$
```

**Pull request closed without merging**
