### PR TITLE
add Windows testing

### PR DESCRIPTION
**Pull request by mschilli87**
see https://github.com/BIMSBbioinfo/ciRcus/issues/36 & https://github.com/BIMSBbioinfo/ciRcus/pull/42

### CODE REVIEW

**Comment by mschilli87** [comment]
@retaj: Why the merge? The tests are still failing aren't they?
Now I cannot re-base on dev anymore until it's fixed upstream.
Also, the badge was still missing.
That's why Iabled this WIP and assigned myself. :wink:

**Comment by retaj** [comment]
I have no idea what happened here 🐙 😱 🙀

**Comment by mschilli87** [comment]
I created a new `dev2` branch which is basically `dev` without this merge.
I re-created this PR as #44 targeting the new branch and I updated #40 & #42 to target the new branch.
So theoretically (if you agree), we can delete the `dev` branch and use `dev2` from now on (until the next merge to `master`).

**Comment by mschilli87** [comment]
@retaj: I rebased `dev` and re-targeted all PRs. So when all tests are through I'll remove `dev2` again. Sorry for the force-push to `dev` but it seemed like the cleanest solution to me.
Let me know if this breaks anything locally for you and I'll help you re-base/merge everything into `dev` again. :wink:

**Pull request merged**
